namespace: rhai-namespace

image:
  repository: registry.redhat.io/rhaiis/vllm-cuda-rhel9
  tag: 3.3
  pullPolicy: IfNotPresent

model:
  hfRepo: RedHatAI/Qwen2.5-Coder-7B-Instruct-FP8-dynamic
  name: qwen-coder
  tensor-parallel-size: 1
  tool-call-parser: hermes

resources:
  limits:
    cpu: "10"
    memory: 16Gi
    nvidia.com/gpu: "1"
  requests:
    cpu: "2"
    memory: 6Gi
    nvidia.com/gpu: "1"

persistence:
  enabled: true
  size: 20Gi
  storageClass: ""

service:
  type: ClusterIP
  port: 8000

route:
  enabled: true

secrets:
  hfSecret: ""
  docker:
    dockercfg: ""